### PR TITLE
Rewrite *again* for new TOC

### LINKED ISSUE #20: Tool no longer works with the redesign
When trying after the redesign, on a new IP that is not banned, I get the following result when running the script:

```sh
┌─[switchblade@Switchblade] - [~/wandering_inn] - [2188]
└─[$] python3 wanderinginn2epub.py                                                                    [8:51:27]
Chapter: 0it [00:00, ?it/s]
Generating ePub file for eBook "The Wandering Inn".
ePub file "./build/The Wandering Inn.epub" successfully generated.
┌─[switchblade@Switchblade] - [~/wandering_inn] - [2189]
└─[$] cat cmd                                                                                         [8:51:38]
python3 wanderinginn2epub.py --volume 1 2 3 4 5 6 7 8 9 --output-by-volume
┌─[switchblade@Switchblade] - [~/wandering_inn] - [2190]
└─[$] $(cat cmd)                                                                                      [8:53:22]
Chapter: 0it [00:00, ?it/s]                                                               | 0/9 [00:00<?, ?it/s]
Generating ePub file for eBook "The Wandering Inn - Volume 1".
ePub file "./build/The Wandering Inn - Volume 1.epub" successfully generated.
Chapter: 0it [00:00, ?it/s]
Generating ePub file for eBook "The Wandering Inn - Volume 2".
ePub file "./build/The Wandering Inn - Volume 2.epub" successfully generated.
Chapter: 0it [00:00, ?it/s]█▎                                                     | 2/9 [00:00<00:00, 10.64it/s]
Generating ePub file for eBook "The Wandering Inn - Volume 3".
ePub file "./build/The Wandering Inn - Volume 3.epub" successfully generated.
Chapter: 0it [00:00, ?it/s]
Generating ePub file for eBook "The Wandering Inn - Volume 4".
ePub file "./build/The Wandering Inn - Volume 4.epub" successfully generated.
Chapter: 0it [00:00, ?it/s]████████████████▋                                      | 4/9 [00:00<00:00, 10.73it/s]
Generating ePub file for eBook "The Wandering Inn - Volume 5".
ePub file "./build/The Wandering Inn - Volume 5.epub" successfully generated.
Chapter: 0it [00:00, ?it/s]
Generating ePub file for eBook "The Wandering Inn - Volume 6".
ePub file "./build/The Wandering Inn - Volume 6.epub" successfully generated.
Chapter: 0it [00:00, ?it/s]████████████████████████████████                       | 6/9 [00:00<00:00, 10.67it/s]
Generating ePub file for eBook "The Wandering Inn - Volume 7".
ePub file "./build/The Wandering Inn - Volume 7.epub" successfully generated.
Chapter: 0it [00:00, ?it/s]
Generating ePub file for eBook "The Wandering Inn - Volume 8".
ePub file "./build/The Wandering Inn - Volume 8.epub" successfully generated.
Chapter: 0it [00:00, ?it/s]███████████████████████████████████████████████▎       | 8/9 [00:00<00:00, 10.74it/s]
Generating ePub file for eBook "The Wandering Inn - Volume 9".
ePub file "./build/The Wandering Inn - Volume 9.epub" successfully generated.
Volume: 100%|█████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 10.74it/s]



```

The ebooks are empty and do not contain any info, even when doing it by volume. I assume there is some issue finding the content or URLs. I have confirmed that I can hit the site, and other scraper can see content.

What logs can I give you to help you fix?

### PR DESCRIPTION
**Pull request by JJTech0130**
New week, new TOC. I rewrote the logic again, should fix it. They removed sectioning things by "book" 😞 
(Fix #20)

### CODE REVIEW

**Comment by przecze** [comment]
didn't notice you created a PR already when I implemented it myself :facepalm: 
Feel free to use some of this if you like it!
```
def get_index(toc_url=r'https://wanderinginn.com/table-of-contents/'):
    page = urlopen(toc_url)
    soup = BeautifulSoup(page, 'lxml')

    index = []
    for volume_wrapper in soup.find_all('div', {'class': 'volume-wrapper'}):
        wrapper_id = volume_wrapper.get('id')
        try:
            volume = int(wrapper_id.replace("vol-","").strip())
        except ValueError:
            print(f"Unable to get volume from volume wrapper id: {wrapper_id}")
            continue

        for chapter_cell in volume_wrapper.find_all('div', {'class': 'body-web table-cell'}):
            chapters = [Chapter(link['href'], link.text, volume, index)
                        for index, link in enumerate(chapter_cell.find_all('a', href=True))]
            if len(chapters) != 1:
                print(f"Unexpected results for chapter cell: {chapter_cell}, {chapters}")
            index.extend(chapters)
    return index
```

**Comment by przecze** [comment]
I just tested your code and it doesn't work for me. I think there's no `volume-header-wrapper` div class anymore
I will open a PR with my implementation, because this seems to be working (at the moment at least)

**Comment by JJTech0130** [comment]
See https://github.com/Patrick-Hogan/wandering_inn/issues/20#issuecomment-1616287339, seems like a new redesign every week so I gave up on PRs

**Comment by przecze** [comment]
ChatGPT API integration maybe?

**Pull request closed without merging**
