### PR TITLE
Add book filtering and fix volume filtering after redesign

### LINKED ISSUE #17: FEATURE REQUEST: Download by "book"
Volumes are now sub-sectioned into "books", and now that there is an agressive rate limit it would be useful to be able to download just a book.

### PR DESCRIPTION
**Pull request by JJTech0130**
Implements https://github.com/Patrick-Hogan/wandering_inn/issues/17, as well as fixing an issue with volume filtering that I didn't notice after the redesign.

Fix https://github.com/Patrick-Hogan/wandering_inn/issues/17

### CODE REVIEW

**Comment by JJTech0130** [comment]
fix #17

**Comment by JJTech0130** [comment]
(I'm banned again, so this could not be fully tested. Someone should test before merging ideally)

**Comment by Shadow-Master** [comment]
I added in your changes and get the following:

```
┌─[switchblade@Switchblade] - [~/wandering_inn] - [2177]
└─[$] python3 wanderinginn2epub.py                                                                    [9:20:59]
Chapter: 0it [00:00, ?it/s]
Generating ePub file for eBook "The Wandering Inn".
ePub file "./build/The Wandering Inn.epub" successfully generated.
```

I have also added in the relative ToC fix in my current script.

EDIT: I just realized that I am banned. Two questions, 1) how long does a ban last, and 2) is there a way to implement a TO so we don't run in to this issue?

**Comment by JJTech0130** [comment]
Are you kidding...
I come back a week later, and looks like the website's been redesigned *again*. I'm just going to close this PR, and make a new one with the new design...

**Pull request closed without merging**
